# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: RTK-Query OpenAPI Codegen Tests
defaults:
  run:
    working-directory: ./packages/rtk-query-codegen-openapi

on:
  push:
    branches:
      - master
    paths:
      - 'packages/rtk-query-codegen-openapi/**'
  pull_request:
    paths:
      - 'packages/rtk-query-codegen-openapi/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - run: yarn install
      - run: yarn test
